### ISSUE TITLE
Cannot access the data download website

### ISSUE THREAD

**Issue by Smilenone** [aristoteleo/spateo-viewer#15]
The website https://spateodata.aristoteleo.com/ for downloading the processed data seems cannot be accessed.

**Comment by Xiaojieqiu** [comment]
@Yao-14 Hey Jiajun, how is the data access now?

**Comment by Yao-14** [comment]
- **Mouse_E9.5_embryo.h5ad:** https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/mouse_E9.5_embryo.h5ad
- **Mouse_E11.5_embryo.h5ad:** https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/mouse_E11.5_embryo.h5ad
- **Mouse_E9.5_heart.h5ad:** https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/mouse_E9.5_heart.h5ad
- **Mouse_E11.5_heart.h5ad:** https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/mouse_E11.5_heart.h5ad
- **Dorosphila_S11_cellbin_clean.h5ad:** https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/dorosphila_S11_cellbin_clean.h5ad
- **Dorosphila_S13_cellbin_clean.h5ad:** https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/dorosphila_S13_cellbin_clean.h5ad

**Comment by Yao-14** [comment]
Hi @Xiaojieqiu @Smilenone , our sample data is currently stored in CNGB. The above is the data and its corresponding download path.

**Comment by Xiaojieqiu** [comment]
@Yao-14 can you please update the page of https://spateodata.aristoteleo.com/ and automatically redirect it to the CNGB pages?

**Comment by Yao-14** [comment]
Sure, i will update the website later!

**Comment by Xiaojieqiu** [comment]
@Yao-14 did you get a chance to update the page?

**Comment by Xiaojieqiu** [comment]
@Sichao25 please help us to update the link. there are several reader is complaining about this

**Comment by Yao-14** [comment]
Thanks to @Sichao25 for the help, the link of spateodata has been updated! Please download sample data from  https://spateodata.aristoteleo.com/

**Comment by Xiaojieqiu** [comment]
great. thanks all! so this issue is fixed and close it now
