### ISSUE TITLE
trame version compatibility

### ISSUE THREAD

**Issue by Harrison-Q-Ma** [aristoteleo/spateo-viewer#5]
Hello, 

trame has released 3.X.X version 2 weeks ago which is incompatible with the current spateo-viewer implementation, specifically line 4 ```from trame.widgets import trame as trame_widgets``` in [stviewer/interactive_app.py](stviewer/interactive_app.py) which raises error 
```ImportError: cannot import name 'trame' from 'trame.widgets' (/Users/harrisonma/opt/anaconda3/lib/python3.9/site-packages/trame/widgets/__init__.py)```. 
I rolled back to trame version 2.5.2 and it worked fine. Please consider changing requirements.txt to limit trame version to be trame>=2.2.5,<3. Thanks.

**Comment by Yao-14** [comment]
Hi @Harrison-Q-Ma , thanks a lot for your suggestion. Currently trame is still in a rapid development stage, so the version of trame may cause spateo-viewer not to work well. Now we will change requirements.txt according to your suggestion, and we will update spateo-viewer after a while.
