### ISSUE TITLE
Feature Request: Arbitrary Shaped Cell Selection Methods and Wayland Support

### ISSUE THREAD

**Issue by Purkinje-cell** [aristoteleo/spateo-viewer#7]
I would like to request the addition of two new features:
1. **Arbitrary Shaped Selection Methods for Cells**
2. **Wayland Support**

#### 1. Arbitrary Shaped Selection Methods for Cells
Currently, cells can only be selected using a rectangular region. It would be beneficial to incorporate arbitrary shaped selection methods that provide more flexibility and precision. This could include options like freeform, circular, polygonal, or other shapes that can help users select cells more accurately based on their specific requirements.

#### 2. Wayland Support

With many Linux distributions, such as Ubuntu 21.04, adopting Wayland as their default display server protocol, it is increasingly important to ensure compatibility. 

Wayland is a modern display server protocol that is designed to be simpler and more efficient than the traditional X Window System (X11). It offers improved security, performance, and support for modern graphics technologies. By supporting Wayland, spateo-viewer can provide a better user experience and stay up-to-date with the latest advancements in the Linux ecosystem.

Currently the `pyautogui` package does not support Wayland yet (https://github.com/asweigart/pyautogui/issues/111). Since Spateo Viewer only uses `pyautogui` for getting the screen resolution, it should be easy to implement an alternative method for obtaining the screen resolution on Wayland systems. This workaround can ensure compatibility without waiting for `pyautogui` to add Wayland support.

**Comment by Yao-14** [comment]
Thanks @Purkinje-cell ,your suggestion is very good. Our article has been published and I will update spateo-viewer in the future.
